<a href="https://colab.research.google.com/github/YaCpotato/ToyBox/blob/master/CatBoostWithIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## CatBoost

[論文](https://arxiv.org/pdf/1706.09516.pdf)

In [0]:
import numpy as np
import matplotlib as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras.utils import np_utils
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix,classification_report
import time
from sklearn import model_selection
import pandas as pd

## データセットロード

In [10]:
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data)
iris_df = iris_df.rename(columns={
    0: 'sepal_length',
    1: 'sepal_width',
    2: 'petal_length',
    3: 'petal_width'})
iris_df['target'] = iris.target
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [0]:
train_df, test_df = model_selection.train_test_split(iris_df, test_size=0.3) # 30%をテストに使う
train_df_y = train_df[['target']]
train_df_x = train_df.copy().drop('target', axis=1)
test_df_y = test_df[['target']]
test_df_x = test_df.copy().drop('target', axis=1)

In [12]:
!pip install catboost

In [0]:
from catboost import CatBoostClassifier
from catboost import Pool

train_pool = Pool(train_df_x, label=[i[0] for i in train_df_y.values])
test_pool = Pool(test_df_x, label=[i[0] for i in test_df_y.values])

In [0]:
cb = CatBoostClassifier(loss_function="MultiClass",classes_count=3)

In [15]:
%%time
cb.fit(train_pool)

0:	learn: 1.0686352	total: 746us	remaining: 746ms
1:	learn: 1.0393285	total: 1.8ms	remaining: 898ms
2:	learn: 1.0143125	total: 2.52ms	remaining: 839ms
3:	learn: 0.9852060	total: 3.56ms	remaining: 887ms
4:	learn: 0.9594827	total: 4.24ms	remaining: 844ms
5:	learn: 0.9300648	total: 4.86ms	remaining: 805ms
6:	learn: 0.9077363	total: 5.53ms	remaining: 785ms
7:	learn: 0.8844129	total: 6.24ms	remaining: 773ms
8:	learn: 0.8596468	total: 6.99ms	remaining: 770ms
9:	learn: 0.8358533	total: 7.61ms	remaining: 753ms
10:	learn: 0.8153009	total: 8.38ms	remaining: 754ms
11:	learn: 0.7979651	total: 9.23ms	remaining: 760ms
12:	learn: 0.7786689	total: 9.95ms	remaining: 755ms
13:	learn: 0.7601515	total: 10.6ms	remaining: 750ms
14:	learn: 0.7393247	total: 11.3ms	remaining: 741ms
15:	learn: 0.7233444	total: 11.9ms	remaining: 731ms
16:	learn: 0.7062546	total: 12.5ms	remaining: 723ms
17:	learn: 0.6893125	total: 13.1ms	remaining: 714ms
18:	learn: 0.6725248	total: 13.7ms	remaining: 707ms
19:	learn: 0.6582922	tot

In [16]:
# テストデータを予測する
Y_pred = cb.predict(test_pool, prediction_type='Class')
Y_test = test_df_y.values
# 精度 (Accuracy) を計算する
from sklearn.metrics import confusion_matrix,classification_report
print (confusion_matrix(Y_test, Y_pred))
print (classification_report(Y_test, Y_pred))

[[17  0  0]
 [ 0 14  1]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.93      0.93      0.93        15
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

